import {WitchGreetingCache,witchEvidence} from './witch-prefetch.js';
import {recentRegionDesigns} from '../content/region-design.js';
import {drawHero} from '../volcanic.js';
import {characterContent} from '../content/characters.js';
import {validateContent} from './contracts.js';
import {generationResponse} from './api-response.js';
export function installBoundaryWitch({runtime,onEnter,fetcher=fetch}){
 const dialog=document.createElement('dialog');dialog.id='boundaryWitch';dialog.setAttribute('aria-labelledby','witchTitle');dialog.innerHTML='<div class="modal-header"><h2 id="witchTitle">Beyond the boundary</h2><button id="leaveWitch" aria-label="Return to the map">✕</button></div><canvas width="320" height="150" aria-label="The witch summons a new landscape"></canvas><p id="witchSpeech" class="modal-note"></p><form><label for="witchWish">What are you looking for?</label><textarea id="witchWish" rows="3" maxlength="1000" required placeholder="A frozen forest with ancient ruins…"></textarea><button class="primary" type="submit">Ask the witch</button></form><p id="witchStatus" role="status" class="modal-note"></p><div class="battle-actions"><button id="witchNarration" class="outline" type="button" aria-pressed="false">Read aloud · off</button><button id="witchRetry" class="outline" hidden>Retry</button><button id="witchEnter" class="primary" hidden>Enter new land</button></div>';document.body.append(dialog);
 let controller,frame,busy=false,phase='question',events=[],result=null,destination,requestId,questionId,warmed=null;
 const speech=dialog.querySelector('#witchSpeech'),status=dialog.querySelector('#witchStatus'),form=dialog.querySelector('form'),input=dialog.querySelector('textarea'),retry=dialog.querySelector('#witchRetry'),enter=dialog.querySelector('#witchEnter');
 function draw(now){if(!dialog.open)return;const c=dialog.querySelector('canvas').getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,t=reduced?0:now/1000;c.fillStyle='#172a29';c.fillRect(0,0,320,150);c.strokeStyle=result?.accent||'#cda662';c.lineWidth=2;for(let ring=0;ring<3;ring++){c.beginPath();c.ellipse(160,120,38+ring*24+(busy?Math.sin(t*3+ring)*5:0),10+ring*5,0,0,Math.PI*2);c.stroke()}for(let i=0;i<22;i++){const a=i*Math.PI/11+t*(busy?1.5:.4),r=65+Math.sin(t+i)*15;c.fillStyle=i%2?'#7daaa0':'#eacb86';c.fillRect(160+Math.cos(a)*r,75+Math.sin(a)*42,3,3)}drawHero(c,160,98,'#416660',2,'',false,{role:'Mage',custom:{...characterContent({heroClass:'Mage'}),weapon:'staff',clothing:'Robe',outfitColor:'#416660',hairColor:'#d4cbb2'},kind:'Spin',attack:busy?(t%1):undefined});c.fillStyle='#263a39';c.beginPath();c.moveTo(138,47);c.lineTo(157,10);c.lineTo(179,47);c.fill();c.fillStyle='#cda662';c.fillRect(137,44,44,5);frame=requestAnimationFrame(draw)}
 async function request(kind,brief,id,signal,evidence=events){for(let attempt=0;attempt<16;attempt++){const r=await fetcher('/api/generation',{method:'POST',headers:{'Content-Type':'application/json'},signal,body:JSON.stringify({id,kind,brief,events:evidence,recentRegions:recentRegionDesigns(runtime.state.regions)})});if(r.status===429){const data=await r.json();if(data.error?.startsWith('Another generation')&&attempt<15){status.textContent='Waiting for the current spell to finish…';await new Promise((resolve,reject)=>{const done=()=>{signal.removeEventListener('abort',cancel);resolve()},timer=setTimeout(done,2000),cancel=()=>{clearTimeout(timer);reject(new DOMException('Cancelled','AbortError'))};signal.addEventListener('abort',cancel,{once:true});if(signal.aborted)cancel()});continue}throw new Error(data.error||'Generation unavailable.')}const data=await generationResponse(r);validateContent(kind,data.content,evidence);return data.content}}
 const greetings=new WitchGreetingCache((evidence,signal)=>request('witch','The traveler is trying to leave the known map. Ask what they seek.',crypto.randomUUID(),AbortSignal.any([signal,AbortSignal.timeout(120000)]),evidence));
 let narration=false;const narrateButton=dialog.querySelector('#witchNarration');
 narrateButton.hidden=!('speechSynthesis' in window);
 function speak(text){if(!narration||!('speechSynthesis' in window))return;speechSynthesis.cancel();const line=new SpeechSynthesisUtterance(text);line.rate=.88;line.pitch=.75;speechSynthesis.speak(line)}
 narrateButton.onclick=()=>{narration=!narration;narrateButton.textContent=`Read aloud · ${narration?'on':'off'}`;narrateButton.setAttribute('aria-pressed',String(narration));if(narration)speak(speech.textContent);else window.speechSynthesis?.cancel()};
 async function generate(){if(busy)return;busy=true;retry.hidden=true;form.querySelector('button').disabled=true;input.disabled=true;controller=new AbortController();const current=controller;const timer=setTimeout(()=>current.abort(),150000);status.textContent=phase==='question'?'Summoning the boundary witch…':'The witch is weaving new land…';try{const prefetched=phase==='question'&&warmed?await warmed.promise:null;const content=prefetched||await request(phase==='question'?'witch':'region',phase==='question'?'The traveler is trying to leave the known map. Ask what they seek.':input.value.trim(),phase==='question'?questionId:requestId,current.signal);if(!dialog.open||controller!==current)return;if(phase==='question'){dialog.querySelector('#witchTitle').textContent=content.name;speech.textContent=content.line;speak(content.line);form.hidden=false;status.textContent='Describe a place, a mood, or what you hope to find.';}else{result=content;speech.textContent=content.witchLine;speak(content.witchLine);form.hidden=true;enter.hidden=false;enter.textContent=`Enter ${content.name}`;status.textContent=content.description;}}catch(e){if(dialog.open&&controller===current){status.textContent=e.name==='AbortError'?'The spell timed out. You can retry or return to the map.':e.message;retry.hidden=false}}finally{clearTimeout(timer);if(controller===current){busy=false;input.disabled=false;form.querySelector('button').disabled=false}}}
 form.onsubmit=e=>{e.preventDefault();if(!input.value.trim()||busy)return;phase='region';requestId=crypto.randomUUID();generate()};retry.onclick=()=>generate();enter.onclick=()=>{if(!result)return;try{onEnter(destination,result,events);dialog.close()}catch(e){status.textContent=e.message}};dialog.querySelector('#leaveWitch').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{controller?.abort();warmed?.controller.abort();warmed=null;window.speechSynthesis?.cancel();controller=null;busy=false;cancelAnimationFrame(frame)});
 return{dialog,prefetch(target){if(dialog.open||runtime.state.jobs.some(j=>['queued','running'].includes(j.status)))return;greetings.prefetch(target,witchEvidence(runtime.state))},open(target){destination=target;result=null;phase='question';questionId=crypto.randomUUID();requestId=crypto.randomUUID();events=witchEvidence(runtime.state);warmed=greetings.take(target,events);speech.textContent='';input.value='';form.hidden=true;retry.hidden=true;enter.hidden=true;dialog.querySelector('#witchTitle').textContent='Beyond the boundary';dialog.showModal();frame=requestAnimationFrame(draw);generate()}};
}
