import test from 'node:test';
import assert from 'node:assert/strict';
import {GameRuntime,SAVE_KEY} from './runtime.js';
import {validateContent} from './contracts.js';
import {GenerationQueue} from './generation.js';
const storage=()=>{const m=new Map();return{getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)}};
function setup(store=storage()){let n=0;const game=new GameRuntime({storage:store,id:()=>`event-${++n}`,clock:()=>1000+n});return game}
function discover(g){for(const room of ['inn','smith','home'])g.record('room_entered',room,`Visited ${room}`)}
function earn(g){discover(g);const q={id:'earned-quest',status:'complete',content:{title:'Earned task',description:'Visited the inn',sourceEventIds:[g.state.events[0].id],objectives:[{type:'visit_room',target:'inn',description:'Visit inn'}]},completed:[true]};g.state.quests.push(q);g.record('quest_completed',q.id,'Completed earned task',{unique:true})}
function offer(g,job){return{name:'Test wings',description:'A test-only attachment.',reason:'Based on recorded exploration.',tradeoff:'Replaces the current awakening.',sourceEventIds:job.eventIds,appearance:[{x:-20,y:-12,w:8,h:3,color:'#ddbb88'}],skill:{name:'Test pulse',description:'An animated pulse.',durationMs:600,cooldownMs:2000,effects:[{shape:'ring',color:'#ddbb88',radius:30,count:12,rotation:1}]}}}
function quest(g,job){return{title:'Test task',description:'Visit the inn.',sourceEventIds:job.eventIds,objectives:[{type:'visit_room',target:'inn',description:'Enter the inn'}]}}
test('discoveries alone never grant an awakening',()=>{const g=setup();discover(g);for(let i=0;i<5;i++)g.record('room_entered','inn','Visited inn');assert.equal(g.state.jobs.filter(j=>j.kind==='awakening').length,0);assert.equal(g.state.events.filter(e=>e.meaningful).length,3);assert.equal(g.state.activeAwakening,null)});
test('generated offers do not apply without acceptance; decline preserves active appearance',()=>{const g=setup();earn(g);const j=g.state.jobs.find(j=>j.kind==='awakening');g.complete(j.id,offer(g,j));assert.equal(g.activeOffer(),undefined);g.decideAwakening(j.id,true);assert.equal(g.activeOffer().id,j.id);const second={...j,id:'second',status:'queued'};g.state.jobs.push(second);g.complete(second.id,offer(g,second));g.decideAwakening(second.id,false);assert.equal(g.activeOffer().id,j.id);g.complete(j.id,offer(g,j));assert.equal(g.state.offers.length,2)});
test('accepted content and factual journal survive reload',()=>{const store=storage(),g=setup(store);earn(g);const j=g.state.jobs.find(j=>j.kind==='awakening');g.complete(j.id,offer(g,j));g.decideAwakening(j.id,true);const restored=setup(store);assert.equal(restored.activeOffer().content.name,'Test wings');assert.equal(restored.state.journal.length,g.state.journal.length)});
test('quest requests deduplicate; only post-acceptance objectives complete',()=>{const g=setup();g.requestQuest();g.requestQuest();assert.equal(g.state.jobs.length,1);const j=g.state.jobs[0];g.complete(j.id,quest(g,j));g.record('room_entered','inn','Visited inn');assert.equal(g.state.quests[0].status,'offered');g.acceptQuest(j.id);g.record('room_entered','inn','Revisited inn');assert.equal(g.state.quests[0].status,'complete');g.record('room_entered','inn','Revisited inn');assert.equal(g.state.events.filter(e=>e.type==='quest_completed').length,1)});
test('contracts reject executable extras, bad references and impossible quests',()=>{const g=setup();earn(g);const j=g.state.jobs.find(j=>j.kind==='awakening'),a=offer(g,j),events=g.context(j).events;assert.throws(()=>validateContent('awakening',{...a,code:'alert(1)'},events));assert.throws(()=>validateContent('awakening',{...a,sourceEventIds:['invented']},events));assert.throws(()=>validateContent('quest',{...quest(g,j),objectives:[{type:'visit_room',target:'Cleave',description:'wrong'}]},events));assert.throws(()=>validateContent('awakening',{...a,appearance:[{x:100,y:0,w:1,h:1,color:'#ffffff'}]},events))});
test('content is validated on restore; interrupted jobs become retryable failures',()=>{const store=storage(),g=setup(store);earn(g);const j=g.state.jobs.find(j=>j.kind==='awakening');g.complete(j.id,offer(g,j));g.decideAwakening(j.id,true);g.state.offers[0].content.appearance[0].x=999;g.state.jobs[0].status='running';g.changed();const restored=setup(store);assert.equal(restored.activeOffer(),undefined);assert.equal(restored.state.jobs[0].status,'failed')});
test('unconfigured provider never sends generation requests',async()=>{const g=setup();earn(g);const calls=[];const q=new GenerationQueue(g,{fetcher:async(url)=>{calls.push(url);return{ok:true,json:async()=>({configured:false})}}});await q.connect();assert.deepEqual(calls,['/api/generation/status']);assert.equal(g.state.jobs.find(j=>j.kind==='awakening').status,'queued')});
test('failed requests remain available for explicit retry',async()=>{const g=setup();earn(g);g.state.jobs=g.state.jobs.filter(j=>j.kind==='awakening');const q=new GenerationQueue(g,{fetcher:async()=>({ok:false,json:async()=>({error:'Unavailable'})})});q.enabled=true;await q.pump();assert.equal(g.state.jobs[0].status,'failed');assert.equal(g.state.offers.length,0);assert.equal(g.state.jobs[0].error,'Unavailable')});
test('a slow response only uses its captured evidence',()=>{const g=setup();earn(g);const j=g.state.jobs.find(j=>j.kind==='awakening');g.record('combo_learned','Cleave','Learned Cinder Cleave');assert.equal(g.context(j).events.length,4);const a=offer(g,j);a.sourceEventIds=[g.state.events.at(-1).id];assert.throws(()=>g.complete(j.id,a))});
test('each completed quest earns one reward, including while an earlier offer is pending',()=>{
 const g=setup();discover(g);g.requestAwakening();assert.equal(g.state.jobs.filter(j=>j.kind==='awakening').length,0);
 earn(g);const job=g.state.jobs.find(j=>j.kind==='awakening');assert.equal(g.context(job).rewardQuestId,'earned-quest');
 job.status='failed';g.requestAwakening('earned-quest');g.retry();assert.equal(job.status,'queued');assert.equal(g.state.jobs.filter(j=>j.kind==='awakening').length,1);
 g.complete(job.id,offer(g,job));g.requestAwakening('earned-quest');assert.equal(g.state.offers.length,1);
 const next={...g.state.quests[0],id:'second-earned'};g.state.quests.push(next);g.record('quest_completed',next.id,'Completed second',{unique:true});assert.equal(g.state.jobs.filter(j=>j.kind==='awakening').length,2);
 g.decideAwakening(job.id,false);g.requestAwakening('earned-quest');g.record('room_entered','inn','Visited again');assert.equal(g.state.jobs.filter(j=>j.kind==='awakening').length,2);
 const reloaded=new GameRuntime({storage:g.storage});reloaded.requestAwakening('earned-quest');assert.equal(reloaded.state.jobs.filter(j=>j.kind==='awakening').length,2);
});
test('old manual requests are cancelled on reload and cannot be retried',()=>{const g=setup();discover(g);g.enqueue('awakening','old-reroll',g.state.events);g.changed();const restored=new GameRuntime({storage:g.storage});assert.equal(restored.state.jobs[0].status,'cancelled');restored.retry();assert.equal(restored.state.jobs[0].status,'cancelled')});
