import test from 'node:test';
import assert from 'node:assert/strict';
import {GameRuntime} from './runtime.js';
import {GenerationQueue} from './generation.js';
import {WorldSimulation} from './world-simulation.js';
import {WorldController} from './world-controller.js';
import {notebookRuntimeFacade,requestNotebook,completeNotebookJob} from './notebook-runtime.js';
import {NOTEBOOK_EXAMPLES as EX,NOTEBOOK_LIMITS,validateNotebookContent,KINDLING_ID} from './notebook-core.js';
const storage=()=>{const m=new Map();return{getItem:k=>m.get(k),setItem:(k,v)=>m.set(k,v)}};
function setup(store=storage()){
 let n=0;const runtime=new GameRuntime({storage:store,id:()=>`test-${++n}`,clock:()=>1000+n});
 const simulation=new WorldSimulation({saved:runtime.state.worldSimulation}),scene={room:'inn',player:{x:400,y:348,direction:'up'},actors:[],hp:280};simulation.sync(scene);
 const controller=new WorldController({runtime,simulation,snapshot:()=>scene,fetcher:()=>{throw new Error('Unexpected provider call')}}),book=notebookRuntimeFacade(runtime,simulation,controller);
 return {runtime,simulation,controller,scene,book,store};
}
const fire=f=>f.simulation.entity(KINDLING_ID).props.onFire;
function write(f){f.book.discoverNotebook();f.book.inscribeNotebook('notebook_object',EX.notebook_object);f.book.inscribeNotebook('notebook_law',EX.notebook_law);}

test('discovering the notebook respects native room and table collision reach',()=>{const f=setup();f.scene.room=null;assert.throws(()=>f.book.discoverNotebook());f.scene.room='inn';f.scene.player={x:230,y:400};assert.throws(()=>f.book.discoverNotebook());f.scene.player={x:400,y:348};assert.equal(f.book.discoverNotebook().kind,'notebook_discovered');assert.equal(f.book.discoverNotebook(),null);assert.equal(f.runtime.state.jobs.length,0);});
test('water only extinguishes after a written law and an explicit use; witness memory cites the actual effect',()=>{const f=setup();f.book.discoverNotebook();f.book.inscribeNotebook('notebook_object',EX.notebook_object);assert.equal(f.book.useNotebook().events.length,0);assert.equal(fire(f),true);f.book.inscribeNotebook('notebook_law',EX.notebook_law);assert.equal(fire(f),true);const result=f.book.useNotebook();assert.equal(fire(f),false);assert.equal(result.quenched.data.causalEventId,result.used.id);assert.equal(result.quenched.data.lawId,f.simulation.state.notebook.laws[0].id);assert.ok(f.simulation.state.actors.player.memories.some(m=>m.eventId===result.quenched.id));assert.ok(!f.simulation.state.actors.rowan.memories.some(m=>m.eventId===result.quenched.id));assert.equal(f.book.useNotebook().events.length,0);assert.equal(f.runtime.state.jobs.length,0);});
test('created objects use the existing pickup, drop, inventory, and reach rules',()=>{const f=setup();write(f);const id=f.simulation.state.notebook.selected,entity=f.simulation.entity(id);assert.equal(entity.location.kind,'ground');assert.equal(f.controller.direct('interact',id).ok,true);assert.deepEqual(f.simulation.entity(id).location,{kind:'held',actor:'player'});assert.ok(f.simulation.publicState().entities.some(e=>e.id===id&&e.location.kind==='held'));assert.ok(f.book.useNotebook().quenched);assert.equal(f.controller.direct('drop',id).ok,true);assert.equal(f.simulation.entity(id).location.kind,'ground');f.scene.player={x:550,y:410};assert.throws(()=>f.book.useNotebook());});
test('disabled laws stop working and a failed combined action rolls back every notebook effect',()=>{const f=setup();write(f);const law=f.simulation.state.notebook.laws[0];f.book.editNotebook(law.id,'toggle');assert.equal(f.book.useNotebook().events.length,0);f.book.editNotebook(law.id,'toggle');const before=structuredClone(f.simulation.state);const result=f.controller.apply({actor:'player',ops:[{kind:'notebook',action:'use',entity:f.simulation.state.notebook.selected,target:KINDLING_ID},{kind:'transfer',entity:'missing',to:'player'}]});assert.equal(result.ok,false);assert.deepEqual(f.simulation.state,before);f.book.editNotebook(law.id,'erase');assert.equal(f.book.useNotebook().events.length,0);});
test('wetness extinguishes and blocks ignition without status-triggered cascades',()=>{const f=setup();f.book.discoverNotebook();f.book.inscribeNotebook('notebook_object',EX.notebook_object);f.book.inscribeNotebook('notebook_law',{...EX.notebook_law,effect:{op:'setStatus',status:'wet',value:'set'}});f.book.inscribeNotebook('notebook_law',{...EX.notebook_law,effect:{op:'setStatus',status:'onFire',value:'set'}});assert.equal(f.book.useNotebook().events.length,2);assert.equal(fire(f),false);assert.equal(f.book.useNotebook().events.length,0);});
test('unsupported data, executable code, extra fields, and excess objects are rejected',()=>{for(const value of [{...EX.notebook_object,code:'alert(1)'},{...EX.notebook_object,kind:'dragon'}])assert.throws(()=>validateNotebookContent('notebook_object',value));assert.throws(()=>validateNotebookContent('notebook_law',{...EX.notebook_law,trigger:'StatusChanged'}));const f=setup();f.book.discoverNotebook();for(let i=0;i<NOTEBOOK_LIMITS.objects;i++)f.book.inscribeNotebook('notebook_object',EX.notebook_object);assert.throws(()=>f.book.inscribeNotebook('notebook_object',EX.notebook_object));const r=f.controller.apply({actor:'player',ops:[{kind:'notebook',action:'use',entity:f.simulation.state.notebook.selected,target:KINDLING_ID,code:'x'}]});assert.equal(r.ok,false);});
test('AI proposal snapshots use observed world events and require explicit acceptance',async()=>{const f=setup();f.book.discoverNotebook();const job=f.book.requestNotebook('notebook_object','A small jar of rainwater');let sent;const queue=new GenerationQueue(f.runtime,{fetcher:async(url,options)=>{sent=JSON.parse(options.body);return{ok:true,json:async()=>({content:EX.notebook_object})}}});queue.enabled=true;await queue.pump();assert.equal(sent.notebook.worldId,f.simulation.state.id);assert.equal(sent.events[0].type,'notebook_discovered');assert.equal(f.book.state.notebook.objects.length,0);f.book.acceptNotebookProposal(job.id);assert.equal(f.book.state.notebook.objects[0].source,'ai');});
test('stale and failed drafts leave world state unchanged',async()=>{const f=setup();f.book.discoverNotebook();const job=f.book.requestNotebook('notebook_object','Water');assert.throws(()=>f.book.requestNotebook('notebook_law','Cool fire'));f.book.inscribeNotebook('notebook_law',EX.notebook_law);f.runtime.complete(job.id,EX.notebook_object);assert.throws(()=>f.book.acceptNotebookProposal(job.id));assert.equal(f.book.state.notebook.objects.length,0);f.book.dismissNotebook(job.id);const failJob=f.book.requestNotebook('notebook_object','Water');const before=structuredClone(f.simulation.state);const queue=new GenerationQueue(f.runtime,{fetcher:async()=>({ok:false,json:async()=>({error:'Unavailable'})})});queue.enabled=true;await queue.pump();assert.equal(failJob.status,'failed');assert.deepEqual(f.simulation.state,before);});
test('shared entity ownership, rules, journal and witnessed consequence survive reload',()=>{const f=setup();write(f);const object=f.simulation.state.notebook.selected;assert.ok(f.controller.direct('interact',object).ok);const result=f.book.useNotebook();f.controller.persist();const restored=setup(f.store);assert.deepEqual(restored.simulation.entity(object).location,{kind:'held',actor:'player'});assert.equal(restored.simulation.state.notebook.laws.length,1);assert.equal(fire(restored),false);assert.equal(restored.simulation.state.notebook.rememberedQuench,result.quenched.id);assert.ok(restored.runtime.state.journal.some(j=>j.title.includes('cleared from')));assert.equal(restored.book.useNotebook().events.length,0);});
