import {generationResponse} from './api-response.js';
import {CLASS_COLORS} from '../content/game-config.js';
import {HAIRSTYLES,CLOTHES,HAIR_COLORS,SKIN_COLORS,OUTFIT_COLORS,WEAPONS,characterContent} from '../content/characters.js';
import {validateContent} from './contracts.js';
import {drawHero} from '../volcanic.js';
import {drawAttachment} from './generated-renderer.js';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function installOnboarding({runtime,onSave,fetcher=fetch}){
 const dialog=document.createElement('dialog');dialog.id='characterCreator';dialog.setAttribute('aria-labelledby','creatorTitle');document.body.append(dialog);
 let draft,controller,busy=false,keepName=false,status='';
 const choices=(field,values)=>values.map(v=>`<button type="button" class="creator-choice ${draft[field]===v?'chosen':''}" data-field="${field}" data-value="${v}" aria-pressed="${draft[field]===v}">${v}</button>`).join('');
 const swatches=(field,values)=>[...new Set([...values,draft[field]])].map(v=>`<button type="button" class="swatch ${draft[field]===v?'chosen':''}" style="--swatch:${v}" data-field="${field}" data-value="${v}" aria-label="${field.replace('Color',' color')} ${v}" aria-pressed="${draft[field]===v}"></button>`).join('');
 function preview(){const c=dialog.querySelector('#creatorPreview').getContext('2d');c.clearRect(0,0,220,200);c.fillStyle='#152729';c.fillRect(0,0,220,200);c.fillStyle='#435449';c.beginPath();c.ellipse(110,164,55,12,0,0,Math.PI*2);c.fill();drawAttachment(c,110,128,3,{appearance:draft.characterArt});drawHero(c,110,128,draft.outfitColor,3,'',false,{role:draft.heroClass,custom:draft});dialog.querySelector('#creatorNamePreview').textContent=draft.name.trim()||'Your next self';dialog.querySelector('#creatorBio').textContent=draft.bio;
 const moves=dialog.querySelector('#creatorMoves');moves.replaceChildren();for(const [key,slot] of [['Space','Slash'],['Q','Heavy'],['E','Spin'],['R','Bash']]){const p=document.createElement('p');p.textContent=`${key} · ${WEAPONS[draft.weapon].moves[slot].name}`;moves.append(p)}}
 function render(){dialog.innerHTML=`<div class="creator-heading"><div><div class="eyebrow">TILTH · YOUR STORY STARTS HERE</div><h2 id="creatorTitle">Who will you become?</h2><p>Choose a starting form. Let your actions write the rest.</p></div>${runtime.state.profile.onboarded?'<button type="button" id="cancelCreator" aria-label="Close character creator">✕</button>':''}</div><form id="creatorForm"><div class="creator-layout"><aside class="creator-preview"><canvas id="creatorPreview" width="220" height="200" aria-label="Live character appearance preview"></canvas><h3 id="creatorNamePreview"></h3><p id="creatorBio"></p><div id="creatorMoves"></div><small>Starting moves are animation previews.</small></aside><div class="creator-fields"><label for="characterName">YOUR NAME</label><div class="name-row"><input id="characterName" maxlength="24" required autocomplete="off" placeholder="What should we call you?" value="${escape(draft.name)}"><button type="button" id="generateName" class="outline">AI name</button></div><fieldset><legend>CLASS</legend><div class="creator-options">${choices('heroClass',Object.keys(CLASS_COLORS))}</div></fieldset><fieldset><legend>HAIR</legend><div class="creator-options">${choices('hairStyle',HAIRSTYLES)}</div><div class="swatches">${swatches('hairColor',HAIR_COLORS)}</div></fieldset><fieldset><legend>SKIN</legend><div class="swatches">${swatches('skinColor',SKIN_COLORS)}</div></fieldset><fieldset><legend>CLOTHING</legend><div class="creator-options">${choices('clothing',CLOTHES)}</div><div class="swatches">${swatches('outfitColor',OUTFIT_COLORS)}</div></fieldset><fieldset><legend>WEAPON</legend><div class="weapon-options">${Object.entries(WEAPONS).map(([id,w])=>`<button type="button" class="weapon-option ${draft.weapon===id?'chosen':''}" data-field="weapon" data-value="${id}" aria-pressed="${draft.weapon===id}"><b>${w.icon} ${w.name}</b><span>${w.description}</span></button>`).join('')}</div></fieldset><section class="creator-ai"><h3>Something no one has seen before.</h3><p>Describe a traveler, or let AI surprise you. You can edit every result.</p><label for="characterBrief">CHARACTER IDEA</label><textarea id="characterBrief" maxlength="1000" rows="3" placeholder="A silver-haired wanderer with a moss-covered cloak and a weathered spear…"></textarea><div class="battle-actions"><button type="button" id="generateCharacter" class="outline">Create from description</button><button type="button" id="randomCharacter" class="outline">Surprise me · AI</button></div>${draft.characterArt.length?'<button type="button" id="clearArt" class="outline">Remove AI details</button>':''}</section></div></div><div class="creator-footer"><p id="creatorStatus" role="status" aria-live="polite">${escape(status)}</p><button type="submit" class="primary" id="saveCharacter">${runtime.state.profile.onboarded?'Save character':'Enter Cinderwatch'} →</button></div></form>`;
  dialog.querySelectorAll('[data-field]').forEach(b=>b.onclick=()=>{draft[b.dataset.field]=b.dataset.value;const brief=dialog.querySelector('#characterBrief').value;render();dialog.querySelector('#characterBrief').value=brief;dialog.querySelector(`[data-field="${b.dataset.field}"][data-value="${b.dataset.value}"]`)?.focus()});
  dialog.querySelector('#characterName').oninput=e=>{draft.name=e.target.value;keepName=Boolean(draft.name.trim());preview()};
  dialog.querySelector('#generateName').onclick=()=>generate('name');dialog.querySelector('#generateCharacter').onclick=()=>generate('description');dialog.querySelector('#randomCharacter').onclick=()=>generate('random');
  if(dialog.querySelector('#clearArt'))dialog.querySelector('#clearArt').onclick=()=>{draft.characterArt=[];render()};
  dialog.querySelector('#cancelCreator')?.addEventListener('click',()=>dialog.close());
  dialog.querySelector('form').onsubmit=e=>{e.preventDefault();if(busy)return;try{draft.name=draft.name.trim();validateContent('character',draft,[]);runtime.finishCharacter(draft);onSave(draft);dialog.close()}catch{dialog.querySelector('#creatorStatus').textContent='Enter a name with 1–24 characters to continue.'}};
  preview();
 }
 async function generate(mode){if(busy)return;const brief=dialog.querySelector('#characterBrief').value.trim();if(mode==='description'&&!brief){dialog.querySelector('#creatorStatus').textContent='Describe your character first, or choose Surprise me.';dialog.querySelector('#characterBrief').focus();return}
  busy=true;controller=new AbortController();const currentController=controller;
  const timer=setTimeout(()=>controller?.abort(),45000);
  dialog.querySelectorAll('form button,form input,form textarea').forEach(el=>el.disabled=true);dialog.querySelector('#creatorStatus').textContent='Creating your draft… You’ll review it before saving.';
  try{const kind=mode==='name'?'name':'character',id=crypto.randomUUID();const r=await fetcher('/api/generation',{method:'POST',headers:{'Content-Type':'application/json'},signal:currentController.signal,body:JSON.stringify({id,kind,mode,brief:mode==='name'?`Suggest a name for this character: ${draft.heroClass}, ${draft.weapon}, ${draft.bio}`:mode==='random'?'Invent a surprising original traveler.':brief,events:[],profile:draft})});const result=await generationResponse(r);validateContent(kind,result.content,[]);if(!dialog.open||currentController!==controller)return;
   if(kind==='name'){draft.name=result.content.name;keepName=true}else{const originalName=draft.name;draft={...result.content};if(keepName&&originalName.trim())draft.name=originalName}
   status='AI draft ready. Adjust anything you like, then save.';
  }catch(e){if(dialog.open&&currentController===controller)status=e.name==='AbortError'?'Generation timed out or was cancelled. Your character is unchanged.':e.message}
  finally{clearTimeout(timer);if(currentController===controller){busy=false;if(dialog.open){render();dialog.querySelector('#characterBrief').value=brief}}}
 }
 dialog.addEventListener('close',()=>{controller?.abort();controller=null;busy=false});dialog.addEventListener('cancel',e=>{if(!runtime.state.profile.onboarded){e.preventDefault();dialog.querySelector('#creatorStatus').textContent='Choose a name and starting character, then enter the world.'}});
 return{open(){draft=characterContent(runtime.state.profile);if(!runtime.state.profile.onboarded)draft.name='';keepName=Boolean(draft.name);status='';render();dialog.showModal();dialog.querySelector('#characterName').focus()},dialog};
}
