import test from 'node:test';
import assert from 'node:assert/strict';
import {regionGrid,standInRegion,RegionAtlas,arrival,edgeAt,neighbor} from './regions.js';
import {validateContent} from './contracts.js';
import {GameRuntime} from './runtime.js';
import {setRegionTerrain,canStand,advance} from '../world.js';
export const region=()=>({name:'Glasswood',description:'A frosted woodland.',witchLine:'A quiet wood waits beyond.',verdict:'welcoming',sourceEventIds:[],theme:'frost',accent:'#aec9ba',enemyCount:0,patches:Array.from({length:6},(_,i)=>({kind:'water',x:3+i*5,y:5+i*3,w:8,h:6})),landmarks:[{name:'Old Lantern',x:8,y:8}]});
function reachable(grid){const todo=[[20,16]],seen=new Set(['20,16']);for(const [x,y] of todo)for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,key=`${nx},${ny}`;if(seen.has(key)||!standInRegion(grid,nx*20+10,ny*20))continue;seen.add(key);todo.push([nx,ny])}return seen}
test('varied terrain keeps all gates, recovery positions, and landmarks reachable',()=>{for(const layout of ['archipelago','river','caldera','grove','ruins'])for(const seed of [1,71,501]){const c={...region(),layout,seed},grid=regionGrid(c),seen=reachable(grid);setRegionTerrain(grid);try{for(const dir of ['up','down','left','right']){const p=arrival(dir);assert.ok(canStand(p.x,p.y),`${layout} ${dir}`);assert.ok(seen.has(`${Math.floor(p.x/20)},${Math.floor((p.y+10)/20)}`),`${layout} ${dir} connected`)}for(const m of c.landmarks)assert.ok(seen.has(`${m.x},${m.y}`));assert.ok(canStand(400,335));assert.equal(canStand(0,300),false);assert.ok(grid.flat().some(v=>['water','lava','trees','rock'].includes(v)))}finally{setRegionTerrain(null)}}});
test('hostile witch consequences require a cited attack on a townsperson',()=>{const c={...region(),verdict:'hostile',enemyCount:2,sourceEventIds:['hit']};assert.throws(()=>validateContent('region',c,[{id:'hit',type:'combat_hit',target:'ash-raider'}]));assert.throws(()=>validateContent('region',c,[{id:'hit',type:'combat_hit',target:'rowan'}]));assert.doesNotThrow(()=>validateContent('region',c,[{id:'hit',type:'combat_hit',target:'clover'}]));assert.doesNotThrow(()=>validateContent('region',region(),[]));assert.throws(()=>validateContent('region',{...c,enemyCount:0},[{id:'hit',type:'combat_hit',target:'clover'}]))});
test('saved regions survive reload and home guidance follows existing connected areas',()=>{const values=new Map(),storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v)},runtime=new GameRuntime({storage}),atlas=new RegionAtlas(runtime);atlas.add('0,-1',region(),[]);atlas.add('1,-1',region(),[]);atlas.add('1,-2',region(),[]);atlas.current='1,-2';assert.equal(atlas.homeDirection(),'down');const restored=new RegionAtlas(new GameRuntime({storage}));assert.deepEqual(restored.regions['1,-2'].content,region());assert.equal(restored.current,'0,0');assert.equal(neighbor('1,-1','left'),'0,-1')});
test('outpost routes trigger before inaccessible edges and generated gates are reversible',()=>{assert.equal(edgeAt({x:400,y:83},'up'),true);assert.equal(edgeAt({x:705,y:475},'right'),true);assert.equal(edgeAt({x:600,y:335},'right'),false);for(const dir of ['up','down','left','right'])assert.equal(edgeAt(arrival(dir),dir,true),false)});

test('macro layouts differ, are deterministic, and have no forced perimeter highway',()=>{const grids=['archipelago','river','caldera','grove','ruins'].map(layout=>regionGrid({...region(),layout,seed:71}));assert.equal(new Set(grids.map(g=>JSON.stringify(g))).size,5);assert.deepEqual(grids[0],regionGrid({...region(),layout:'archipelago',seed:71}));assert.ok(grids[0][0].some(t=>!['path','bridge'].includes(t)))});
test('recent layouts are excluded from the next generation choices',async()=>{const {availableLayouts}=await import('../content/region-design.js');assert.deepEqual(availableLayouts([{layout:'river'},{layout:'grove'}]),['archipelago','caldera','ruins'])});
