import {replaceContent} from './stable-content.js';
import {canvasViewport,clientToWorld,entitiesInViewport,entityPosition,playerViewForViewport} from './world-viewport.js';
import {worldObjectBounds} from './world-object-renderer.js';
export {drawWorldObjects} from './world-object-renderer.js';
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function installWorldUI({controller,simulation,canvas,player,redraw,sound=()=>{},showJournal=()=>{},showTraits=()=>{}}){
 const panel=document.createElement('details');panel.id='worldActions';panel.open=true;
 panel.innerHTML='<summary><span>✦ WHAT DO YOU DO?</span><small id="worldRequestState">Your words, your approach</small></summary><div class="world-action-content"><div class="world-character-heading"><span class="world-label">YOUR CHARACTER</span><button id="worldTraits" type="button">Traits ↗</button></div><div id="worldStats"></div><div id="worldNearby"></div><div id="worldSelection"></div><div id="worldInventory"></div><form id="worldActionForm"><label for="worldIntent">Describe any action</label><div class="world-input-row"><textarea id="worldIntent" rows="2" maxlength="1200" placeholder="Distract Rowan, offer Clover a meal, or try something unexpected…"></textarea><button class="primary" type="submit">Act ↗</button></div></form><p id="worldMessage" role="status" aria-live="polite"></p><div class="world-action-footer"><span>Walking never waits for a reply.</span><button id="worldJournal" type="button">Journal</button><button id="worldReconnect" type="button">Reconnect</button></div></div>';
 document.body.append(panel);let selected=null;const input=panel.querySelector('textarea');
 function viewport(){const v=window.visualViewport;return canvasViewport({bounds:canvas.getBoundingClientRect(),width:canvas.width,height:canvas.height,position:player(),viewport:{left:v?.offsetLeft??0,top:v?.offsetTop??0,width:v?.width??window.innerWidth,height:v?.height??window.innerHeight}});}
 function render(){const state=simulation.publicState(),entities=state.entities||[],position={...player(),room:state.room};const visible=entitiesInViewport(entities,viewport(),state.room,worldObjectBounds);
  const obligations=state.issues.filter(issue=>issue.actor==='player'&&issue.status==='open');
  replaceContent(panel.querySelector('#worldStats'),`<span>◆ ${state.player.coins} coins · Fatigue ${state.player.fatigue}</span>${obligations.map(issue=>`<button data-world-settle="${escape(issue.id)}">Settle supplies · ${issue.amount} coins</button>`).join('')}${state.player.evidence.length?`<details class="world-reputation"><summary>Your choices have left a mark</summary>${state.player.evidence.slice(-3).map(e=>`<p>${escape(e.text)}</p>`).join('')}</details>`:''}`);
  replaceContent(panel.querySelector('#worldNearby'),visible.length?'<span class="world-label">IN VIEW</span>'+visible.map(entity=>`<button type="button" data-world-select="${escape(entity.id)}" class="${selected===entity.id?'selected':''}">${escape(entity.name)}</button>`).join(''):'<span class="world-label">No people or objects on screen.</span>');
  const inventory=entities.filter(e=>e.location.kind==='held'&&e.location.actor==='player');const entity=entities.find(e=>e.id===selected);const condition=state.actors.find(actor=>actor.id===selected);const clues=state.player.memories.filter(memory=>memory.kind==='discovery'&&memory.subject===selected);const held=entity?.location.kind==='held'&&entity.location.actor==='player';const targetPosition=entityPosition(entity,entities,position);const reach=held?0:targetPosition?Math.hypot(targetPosition.x-position.x,targetPosition.y-position.y):Infinity;const interactRange=entity?.kind==='actor'?240:80;const contents=entity?.props.container&&entity.props.open?entities.filter(e=>e.location.kind==='contained'&&e.location.container===entity.id):[];
  replaceContent(panel.querySelector('#worldSelection'),entity?`<div class="world-selected-copy"><b>${escape(entity.name)}</b><p>${escape(entity.description)}</p>${reach>interactRange?'<p class="world-range-hint">Walk closer to interact.</p>':''}${clues.map(clue=>`<blockquote>${escape(clue.text)}</blockquote>`).join('')}${condition?`<p>${escape(condition.mood)} · ${condition.wakefulness} · fatigue ${condition.fatigue}</p>`:''}</div>${entity.props.container&&entity.props.open?`<div class="world-contents"><span class="world-label">CONTENTS</span>${contents.length?contents.map(item=>`<button data-world-select="${escape(item.id)}">${escape(item.name)}</button>`).join(''):'<span class="world-select-hint">Empty</span>'}</div>`:''}${entity.location.kind==='contained'?`<button class="world-container-back" data-world-select="${escape(entity.location.container)}">← Back to container</button>`:''}<div class="world-context-buttons"><button data-world-direct="inspect" data-world-entity="${escape(entity.id)}" ${reach>110?'disabled data-out-of-reach="true"':''}>Examine</button><button data-world-direct="interact" data-world-entity="${escape(entity.id)}" ${reach>interactRange?'disabled data-out-of-reach="true"':''}>${entity.kind==='actor'?'Talk':held&&entity.props.food?'Eat':held&&entity.props.heal?'Use':entity.props.open!==undefined?(entity.props.open?'Close':'Open'):entity.props.mechanism?'Activate':held?'Use':'Pick up'}</button>${entity.kind==='actor'?inventory.map(item=>`<button data-world-give="${escape(item.id)}" data-world-recipient="${escape(entity.id)}" ${reach>80?'disabled data-out-of-reach="true"':''}>Give ${escape(item.name)}</button>`).join(''):''}${held?`<button data-world-direct="drop" data-world-entity="${escape(entity.id)}">Drop</button>`:''}</div>`:'<p class="world-select-hint">Click a person or object in the world to interact.</p>');
  replaceContent(panel.querySelector('#worldInventory'),inventory.length?'<span class="world-label">CARRYING</span>'+inventory.map(e=>`<button data-world-select="${escape(e.id)}">${escape(e.name)}</button>`).join(''):'');
  panel.querySelectorAll('[data-world-direct],[data-world-give],[data-world-settle]').forEach(button=>button.disabled=controller.playerPending||button.dataset.outOfReach==='true');
  panel.querySelector('button[type=submit]').disabled=controller.playerPending||!controller.enabled;
  panel.querySelector('#worldRequestState').textContent=controller.playerPending?'Considering your words…':controller.worker?'Someone is responding…':controller.enabled?'Your words, your approach':'Direct play · storyteller offline';
  panel.querySelector('#worldMessage').textContent=controller.status||'';
  panel.querySelector('#worldReconnect').hidden=controller.enabled&&!controller.failed.size;
 }
 panel.addEventListener('click',event=>{const select=event.target.closest('[data-world-select]');if(select){selected=select.dataset.worldSelect;render();redraw();}const settlement=event.target.closest('[data-world-settle]');if(settlement){controller.settle(settlement.dataset.worldSettle);render();redraw();}const give=event.target.closest('[data-world-give]');if(give){controller.give(give.dataset.worldGive,give.dataset.worldRecipient);render();redraw();}const action=event.target.closest('[data-world-direct]');if(action){sound('select');controller.direct(action.dataset.worldDirect,action.dataset.worldEntity);render();redraw();}});
 panel.querySelector('form').addEventListener('submit',async event=>{event.preventDefault();const words=input.value.trim();if(!words)return;const result=await controller.submit(words);if(result.ok&&input.value.trim()===words)input.value='';render();redraw();});
 input.addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();panel.querySelector('form').requestSubmit();}});
 panel.querySelector('#worldReconnect').onclick=()=>controller.connect();panel.querySelector('#worldJournal').onclick=showJournal;panel.querySelector('#worldTraits').onclick=showTraits;
 canvas.addEventListener('click',event=>{const view=viewport(),point=clientToWorld({x:event.clientX,y:event.clientY},view);if(!point)return;const state=simulation.publicState();const targets=entitiesInViewport(state.entities,view,state.room,worldObjectBounds).map(e=>({e,d:Math.hypot(e.location.x-point.x,e.location.y-point.y)})).sort((a,b)=>a.d-b.d);if(targets[0]?.d<32){selected=targets[0].e.id;panel.open=true;render();redraw();}});
 window.addEventListener('resize',render);window.addEventListener('scroll',render,{passive:true});window.visualViewport?.addEventListener('resize',render);
 return{render,playerView(){return playerViewForViewport(simulation.view('player'),simulation.publicState(),viewport(),worldObjectBounds)},get selected(){return selected},focus(){panel.open=true;input.focus();},select(id){selected=id;panel.open=true;render();redraw();}};
}
