import test from 'node:test';import assert from 'node:assert/strict';
import {DungeonRooms} from './dungeon-rooms.js';
const scene={title:'Ember Hall',narration:'A dragon guards the hall.',goal:'Defeat the dragon and secure a relic.',theme:'volcanic',layout:'ruins',seed:411,enemies:[{name:'Ashwing',kind:'dragon',color:'#ae7945',description:'A fierce dragon'}],landmarks:[{name:'The Seal',kind:'shrine'}],suggestions:['Inspect the seal','Challenge the dragon']};
function setup(options={}){let resolver;const dm={configured:true,async generate(kind,context){if(kind==='scene')return structuredClone(scene);if(options.delay)return new Promise(r=>resolver=r);return {kind:context.intent.kind,targetId:context.intent.targetId,difficulty:'easy',successText:'Your resolve holds.',failureText:'The attempt falters.',suggestions:['Press on','Regroup']}}};const tables=new DungeonRooms(dm,{roll:()=>15,...options});const first=tables.create({name:'Ari',heroClass:'Warrior'});const second=tables.join(first.code,{name:'Bea',heroClass:'Healer'});return {tables,first,second,dm,resolve:value=>resolver(value)}}
test('four seats enforced, no late joins, and private tokens never enter shared state',async()=>{const {tables,first,second}=setup();tables.join(first.code,{name:'Cai',heroClass:'Mage'});tables.join(first.code,{name:'Dee',heroClass:'Rogue'});assert.throws(()=>tables.join(first.code,{name:'Eve',heroClass:'Warrior'}),/full/);assert.throws(()=>tables.authorize(first.code,'wrong'),/valid/);const {r,p}=tables.authorize(first.code,first.token);const view=tables.snapshot(r,p);assert.equal(view.capacity,4);assert.equal(JSON.stringify(view).includes(first.token),false);assert.equal(JSON.stringify(view).includes(second.token),false);tables.begin(r,p);await r.pending;tables.leave(r,r.players[3]);assert.throws(()=>tables.join(first.code,{name:'Eve',heroClass:'Warrior'}),/started/)});
test('only host starts; all party members receive the same chapter and turn',async()=>{const {tables,first,second}=setup();const a=tables.authorize(first.code,first.token),b=tables.authorize(first.code,second.token);assert.throws(()=>tables.begin(a.r,b.p),/host/);tables.begin(a.r,a.p);assert.equal(tables.snapshot(a.r,b.p).busy,true);await a.r.pending;assert.equal(a.r.chapter,1);assert.equal(tables.snapshot(a.r,a.p).scene.title,tables.snapshot(a.r,b.p).scene.title);assert.throws(()=>tables.act(a.r,b.p,{kind:'guard',actionId:'wrong-turn-1',targetId:b.p.id}),/turn/)});
test('simultaneous and repeated actions do not spend two turns',async()=>{const {tables,first,second,resolve}=setup({delay:true});const {r,p}=tables.authorize(first.code,first.token);tables.begin(r,p);await r.pending;const cmd={kind:'guard',targetId:p.id,actionId:'guard-once-1'};tables.act(r,p,cmd);await Promise.resolve();assert.equal(r.busy,true);assert.doesNotThrow(()=>tables.act(r,p,cmd));assert.throws(()=>tables.act(r,p,{...cmd,actionId:'guard-twice-2'}),/resolving/);resolve({kind:'guard',targetId:p.id,difficulty:'easy',successText:'Guard up.',failureText:'No.',suggestions:[]});await r.pending;assert.equal(tables.current(r).id,second.playerId);const version=r.version;tables.act(r,p,cmd);assert.equal(r.version,version);assert.equal(r.log.filter(l=>l.speaker==='Dungeon Master'&&l.text==='Guard up.').length,1)});
test('bad AI targets do not change HP or spend the turn and can be retried',async()=>{const {tables,first,dm}=setup();const {r,p}=tables.authorize(first.code,first.token);tables.begin(r,p);await r.pending;dm.generate=async()=>({kind:'attack',targetId:'invented',difficulty:'easy',successText:'No',failureText:'No'});tables.act(r,p,{kind:'improvise',text:'I attack',actionId:'bad-ruling-1'});await r.pending;assert.ok(r.error);assert.equal(tables.current(r).id,p.id);assert.equal(r.busy,false);assert.equal(p.hp,p.maxHp)});
test('movement distance and terrain are authoritative; host transfers on leave',async()=>{const {tables,first,second}=setup();const {r,p}=tables.authorize(first.code,first.token);tables.begin(r,p);await r.pending;assert.throws(()=>tables.act(r,p,{kind:'move',x:0,y:0,actionId:'move-too-far'}),/Move up to/);assert.throws(()=>tables.act(r,p,{kind:'move',x:'oops',y:30,actionId:'move-invalid'}),/Move up to/);tables.leave(r,p);assert.equal(r.host,second.playerId);assert.equal(tables.current(r).id,second.playerId)});
test('server checks downed targets, healing charges, and completion instead of trusting narrative',async()=>{const {tables,first}=setup();const {r,p}=tables.authorize(first.code,first.token);tables.begin(r,p);await r.pending;p.heals=0;assert.throws(()=>tables.act(r,p,{kind:'heal',targetId:p.id,actionId:'heal-none-1'}),/charges/);r.scene.creatures.forEach(e=>e.hp=0);tables.finishTurn(r);assert.equal(r.phase,'playing');r.scene.props[0].secured=true;tables.finishTurn(r);assert.equal(r.phase,'cleared');r.chapter=3;tables.finishTurn(r);assert.equal(r.phase,'won')});
test('offline turns skip to an online survivor and reconnect restores the same seat',async()=>{let time=1000;const {tables,first,second}=setup({clock:()=>time});const {r,p}=tables.authorize(first.code,first.token);tables.begin(r,p);await r.pending;time=70000;const b=tables.authorize(first.code,second.token);tables.snapshot(r,b.p);assert.equal(tables.current(r).id,second.playerId);assert.equal(r.host,second.playerId);const restored=tables.authorize(first.code,first.token);assert.equal(restored.p.id,p.id);assert.equal(r.players.length,2)});
test('a successful attack applies server dice damage and guarded retaliation is bounded',async()=>{
 const {tables,first}=setup({roll:sides=>sides});const {r,p}=tables.authorize(first.code,first.token);tables.begin(r,p);await r.pending;const enemy=r.scene.creatures[0];p.x=enemy.x;p.y=enemy.y+20;const hp=enemy.hp;
 tables.act(r,p,{kind:'attack',targetId:enemy.id,actionId:'strike-once-1'});await r.pending;assert.equal(enemy.hp,hp-18);assert.ok(r.log.some(l=>l.kind==='roll'&&l.text.includes('d20 20')));
 r.players.forEach(v=>{v.x=enemy.x;v.y=enemy.y+20;v.guard=true});const target=r.players[0],before=target.hp;tables.enemies(r);assert.ok(before-target.hp<=6);assert.equal(target.guard,false);
});
