import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {generationApi} from './generation-api.js';
async function request(api,body,url='/api/generation',method='POST'){
 const req=Readable.from(body?[JSON.stringify(body)]:[]);Object.assign(req,{url,method,headers:{host:'localhost:5173',origin:'http://localhost:5173'}});
 let data,status;const res={set statusCode(n){status=n},setHeader(){},end(v){data=JSON.parse(v)}};await api(req,res,()=>{});return{status,data};
}
const input={id:'one',kind:'journal',events:[{id:'e1',type:'room_entered',target:'inn',label:'Visited inn'}],profile:{},pastQuests:[]};
test('no key means no upstream call',async()=>{let count=0;const api=generationApi({},()=>count++);assert.equal((await request(api,input)).status,503);assert.equal(count,0)});
test('valid responses are cached and ID reuse with different evidence is rejected',async()=>{let count=0;const api=generationApi({OPENAI_API_KEY:'test-only',OPENAI_MODEL:'test-model'},async()=>{count++;return{ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({title:'Visit',summary:'Entered the inn.',sourceEventIds:['e1']})}]}]})}});assert.equal((await request(api,input)).status,200);assert.equal((await request(api,input)).status,200);assert.equal(count,1);assert.equal((await request(api,{...input,events:[{...input.events[0],label:'Different'}]})).status,409)});
test('refusals and incomplete outputs never become content',async()=>{for(const result of [{status:'incomplete'},{status:'completed',output:[{content:[{type:'refusal'}]}]}]){const api=generationApi({OPENAI_API_KEY:'test-only',OPENAI_MODEL:'test-model'},async()=>({ok:true,json:async()=>result}));const r=await request(api,input);assert.ok(r.status>=400);assert.equal(r.data.content,undefined)}});
test('quest requests include objective constraints and repeated API outputs are rejected',async()=>{let captured;const api=generationApi({OPENAI_API_KEY:'test-only',OPENAI_MODEL:'test-model'},async(url,options)=>{captured=JSON.parse(JSON.parse(options.body).input);return{ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({title:'Different title',description:'Same objective',sourceEventIds:['e1'],objectives:[{type:'visit_room',target:'home',description:'Go home'}]})}]}]})}});const r=await request(api,{...input,kind:'quest',pastQuests:[{title:'Previous',objectives:[{type:'visit_room',target:'home'}]}]});assert.equal(r.status,422);assert.equal(captured.questConstraints.allowedObjectives.some(o=>o.target==='home'),false)});
test('character description, random, and name requests use their own contracts',async()=>{const {DEFAULT_CHARACTER}=await import('../content/characters.js');for(const mode of ['description','random','name']){let context;const content=mode==='name'?{name:'Sable'}:{...DEFAULT_CHARACTER,name:'Sable'};const api=generationApi({OPENAI_API_KEY:'test-only',OPENAI_MODEL:'test-model'},async(url,options)=>{const payload=JSON.parse(options.body);context=JSON.parse(payload.input);return{ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(content)}]}]})}});const r=await request(api,{id:mode,kind:mode==='name'?'name':'character',mode,brief:'A quiet traveler with a bow',events:[],profile:{}});assert.equal(r.status,200);assert.equal(context.mode,mode);assert.equal(r.data.content.name,'Sable')}});
test('reaction route grounds the speaker in a recorded hit and supplies its personality',async()=>{let context;const api=generationApi({OPENAI_API_KEY:'test',OPENAI_MODEL:'test'},async(url,options)=>{context=JSON.parse(JSON.parse(options.body).input);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({speaker:'rowan',line:'Back off!',sourceEventIds:['hit']})}]}]})});const body={id:'reaction',kind:'reaction',events:[{id:'hit',type:'combat_hit',target:'rowan',label:'Struck Rowan outdoors'}]};const result=await request(api,body);assert.equal(result.status,200);assert.equal(context.speaker.id,'rowan');assert.match(context.scene,/Outdoors/);assert.equal((await request(api,{...body,id:'invalid',events:[{...body.events[0],target:'invented'}]})).status,400)});
test('awakening API requires a quest completion and returns the same reward for repeated requests',async()=>{
 let calls=0;const move={style:'arc',damage:20,range:45,hits:1,color:'#ffbb66'};
 const content={name:'Reward',description:'A reward',reason:'Completed quest',tradeoff:'Replaces awakening',sourceEventIds:['done'],appearance:[{x:0,y:0,w:1,h:1,color:'#ffbb66'}],skill:{name:'Arc',description:'Sweeping arc',durationMs:600,cooldownMs:2000,effects:[{shape:'ring',color:'#ffbb66',radius:40,count:8,rotation:1}],move,combo:{name:'Spiral',steps:['Heavy','Spin','Bash'],move:{...move,style:'spiral'}}}};
 const api=generationApi({OPENAI_API_KEY:'test',OPENAI_MODEL:'test'},async()=>{calls++;return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(content)}]}]})});
 assert.equal((await request(api,{...input,kind:'awakening'})).status,400);assert.equal(calls,0);
 const body={id:'reward1',kind:'awakening',rewardQuestId:'quest1',events:[{id:'done',type:'quest_completed',target:'quest1',label:'Completed task'}]};
 assert.equal((await request(api,body)).status,200);const repeated=await request(api,{...body,id:'reward2'});assert.equal(repeated.status,200);assert.deepEqual(repeated.data.content,content);assert.equal(calls,1);
});
