import {CLASSES,COLORS} from './contracts.js';
import {creature,hero,background,effect} from './art.js';
const $=s=>document.querySelector(s),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const canvas=$('#tableWorld'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
let chosen='Warrior',session=null,state=null,mode='attack',sending=false,polling=false,notice='',noticeUntil=0,sceneKey='',terrain=null,lastLog='',lastFrame=0;
const effects=[],seenEffects=new Set(),positions=new Map();
const descriptions={Warrior:'Hold the front line. A sturdy sword fighter with 46 HP.',Mage:'Bend the battle at range. A spellcaster with 32 HP.',Rogue:'Strike from a distance. A cunning archer with 36 HP.',Healer:'Keep the party standing. Three healing charges and 38 HP.'};
const lobbyScene={title:'The waiting fire',theme:'volcanic',layout:'ruins',seed:4312,enemies:[{name:'The old guardian',kind:'dragon',color:'#766951'}],landmarks:[{name:'The oathstone',kind:'shrine'},{name:'Watchfire',kind:'camp'}]};
terrain=background(lobbyScene);
const invited=new URL(location.href).searchParams.get('room');if(invited)$('#roomCode').value=invited.toUpperCase().slice(0,6);
function classes(){ $('#classChoices').innerHTML=CLASSES.map(c=>`<button type="button" data-class="${c}" aria-pressed="${c===chosen}">${c}</button>`).join('');$('#classDescription').textContent=descriptions[chosen];document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{chosen=b.dataset.class;classes()});const c=$('#seatPreview').getContext('2d');c.clearRect(0,0,140,110);hero(c,{id:'preview',x:70,y:70,name:'',heroClass:chosen,color:COLORS[CLASSES.indexOf(chosen)],weapon:chosen==='Warrior'?'sword':chosen==='Rogue'?'bow':'staff',hp:1},performance.now(),true);}
classes();if(matchMedia('(max-width:650px)').matches){$('#chronicle').classList.add('collapsed');$('#toggleChronicle').setAttribute('aria-expanded','false')}
async function api(path,{method='GET',body,auth=true}={}){const res=await fetch(`/api/dungeon${path}`,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(auth&&session?{Authorization:`Bearer ${session.token}`}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(12000)});let data;try{data=await res.json()}catch{throw new Error('The table server is unavailable. Try again.')}if(!res.ok)throw Object.assign(new Error(data.error||'Request failed.'),{status:res.status});return data;}
function saveSession(value){session=value;try{if(value)sessionStorage.setItem('tilth-table-seat',JSON.stringify(value));else sessionStorage.removeItem('tilth-table-seat')}catch{}}
function message(text){notice=text;noticeUntil=Date.now()+6000;$('#tableStatus').textContent=text;}
async function enter(join){if(sending)return;const name=$('#playerName').value.trim();if(!name){$('#playerName').reportValidity();return}const code=$('#roomCode').value.trim().toUpperCase();if(join&&!/^[A-Z0-9]{6}$/.test(code)){ $('#lobbyError').textContent='Enter the six-character room code.';return}
 sending=true;$('#lobbyError').textContent=join?'Finding your party…':'Preparing your table…';try{const data=await api(join?`/rooms/${code}/join`:'/rooms',{method:'POST',auth:false,body:{name,heroClass:chosen,wish:$('#campaignWish').value.trim()}});saveSession(data);lastLog='';sceneKey='';await poll();$('#roomDialog').showModal();}catch(e){$('#lobbyError').textContent=e.message}finally{sending=false}}
$('#seatForm').onsubmit=e=>{e.preventDefault();enter(false)};$('#joinRoom').onclick=()=>enter(true);
function apply(next){if(!session||next.code!==session.code)return;state=next;$('#lobby').hidden=true;$('#gameHud').hidden=false;
 if(next.scene&&sceneKey!==`${next.code}:${next.chapter}`){sceneKey=`${next.code}:${next.chapter}`;terrain=background(next.scene);effects.length=0;positions.clear();}
 for(const e of next.effects||[])if(!seenEffects.has(e.id)){seenEffects.add(e.id);if(Date.now()-e.time<3500)effects.push({...e,localTime:performance.now()})}if(seenEffects.size>300)seenEffects.clear();
 render();paint();}
async function poll(){if(!session||polling)return;polling=true;const code=session.code;try{const next=await api(`/rooms/${code}`);if(session?.code===code)apply(next)}catch(e){if(e.status===401||e.status===404){saveSession(null);state=null;$('#lobby').hidden=false;$('#gameHud').hidden=true;$('#roomDialog').close();$('#lobbyError').textContent=e.message}else message('Reconnecting to the table…')}finally{polling=false}}
setInterval(poll,900);
function myTurn(){return state?.phase==='playing'&&state.turn===session?.playerId&&!state.busy&&!sending;}
function render(){if(!state)return;const me=state.players.find(p=>p.id===session.playerId),actor=state.players.find(p=>p.id===state.turn);$('#roomCodeLabel').textContent=state.code;$('#chapterLabel').textContent=state.phase==='lobby'?`${state.players.length} / 4 TRAVELERS`:`CHAPTER ${state.chapter} / 3 · ROUND ${state.round}`;$('#sceneTitle').textContent=state.scene?.title||'Around the fire';
 $('#partyStrip').innerHTML=state.players.map(p=>`<div class="party-seat ${p.id===state.turn&&state.phase==='playing'?'active':''}" data-player="${p.id}" role="button" tabindex="0" aria-label="Target ${escape(p.name)}"><div class="party-name"><span>${escape(p.name)}${p.id===me?.id?' · you':''}</span><small>${p.hp}/${p.maxHp}</small></div><div class="party-health"><span style="width:${p.hp/p.maxHp*100}%"></span></div><div class="party-info">${p.heroClass} · ${p.hp<=0?'fallen':!p.online?'away':p.guard?'guarding':`${p.heals} heal${p.heals===1?'':'s'}`}</div></div>`).join('');
 document.querySelectorAll('[data-player]').forEach(el=>{el.onclick=()=>chooseTarget(el.dataset.player);el.onkeydown=e=>{if(e.key==='Enter')chooseTarget(el.dataset.player)}});
 $('#objective').textContent=state.phase==='lobby'?'Share the room code. The host starts when everyone is here.':state.phase==='won'?'The expedition is complete. Your party holds the final relic.':state.phase==='lost'?'Your party has fallen. A new table means a new tale.':state.phase==='cleared'?'Chapter secured. Open ROOM to travel onward.':`${state.scene.goal} · ${state.scene.creatures.filter(e=>e.hp<=0).length}/${state.scene.creatures.length} threats defeated · ${state.scene.props.some(p=>p.secured)?'relic secured':'find a relic'}`;
 const logKey=state.log.at(-1)?.id||'empty';if(logKey!==lastLog){const log=$('#storyLog'),atBottom=log.scrollHeight-log.scrollTop-log.clientHeight<60;log.innerHTML=state.log.slice(-35).map(l=>`<div class="story-entry ${l.kind}"><strong>${escape(l.speaker)}</strong>${escape(l.text)}</div>`).join('')||'<p class="story-entry">The dungeon master is waiting for the party.</p>';if(atBottom)log.scrollTop=log.scrollHeight;lastLog=logKey;}
 $('#turnLabel').textContent=state.busy?'The dungeon master is considering…':state.phase==='lobby'?'Gather your companions':state.phase==='won'?'A tale worth remembering':state.phase==='lost'?'The fire grows quiet':state.phase==='cleared'?'The road opens ahead':myTurn()?`Your turn · ${Math.max(0,Math.round(100-me.moved))} movement left`:`${actor?.name||'A companion'}’s turn`;
 document.querySelectorAll('[data-action]').forEach(b=>{b.disabled=!myTurn();b.setAttribute('aria-pressed',String(mode===b.dataset.action))});$('#actionIdea').disabled=!myTurn();$('#improviseButton').disabled=!myTurn();
 const targets=mode==='heal'?state.players.filter(p=>p.hp>0):mode==='interact'?state.scene?.props.filter(p=>!p.secured)||[]:state.scene?.creatures.filter(p=>p.hp>0)||[];const selected=$('#targetPicker').value;const options=targets.map(t=>`<option value="${t.id}">${escape(t.name)}${t.hp!==undefined?` · ${t.hp} HP`:''}</option>`).join('');if($('#targetPicker').innerHTML!==options){$('#targetPicker').innerHTML=options;if(targets.some(t=>t.id===selected))$('#targetPicker').value=selected}$('#targetPicker').disabled=!myTurn();$('#targetAction').disabled=!myTurn()||!targets.length;$('#targetRow').hidden=mode==='move';$('#movePad').hidden=mode!=='move';$('#movePad').querySelectorAll('button').forEach(b=>b.disabled=!myTurn());
 $('#actionHint').textContent=mode==='move'?'Click clear ground to move. WASD / arrows also work.':mode==='heal'?'Select a companion on the map or party list.':mode==='interact'?'Click an unclaimed landmark on the map.':mode==='attack'?'Click a living enemy. Move closer if needed.':'Describe what you want to do below.';
 const suggestions=(state.scene?.suggestions||[]).slice(0,2);const suggestionKey=suggestions.join('|');if($('#suggestions').dataset.key!==suggestionKey){$('#suggestions').dataset.key=suggestionKey;$('#suggestions').innerHTML=suggestions.map(s=>`<button data-suggestion="${escape(s)}">${escape(s)}</button>`).join('');$('#suggestions').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#actionIdea').value=b.dataset.suggestion;$('#actionIdea').focus()})}$('#suggestions').querySelectorAll('button').forEach(b=>b.disabled=!myTurn());
 $('#roomSummary').textContent=`Room ${state.code} · ${state.players.length} / ${state.capacity} players. ${state.wish}`;$('#startAdventure').hidden=state.host!==me?.id||!['lobby','cleared'].includes(state.phase);$('#startAdventure').disabled=state.busy||!state.configured;$('#startAdventure').textContent=state.phase==='cleared'?'Travel to the next chapter':'Begin the adventure';$('#leaveRoom').disabled=state.busy;$('#roomHelp').textContent=!state.configured?'Add OPENAI_API_KEY to the server to connect the dungeon master.':state.busy?'Astra is preparing the next moment. Everyone will see the result together.':state.phase==='lobby'?'Invite up to three companions before starting. Reloading this tab keeps your seat.':state.host===me?.id?'You are the host. Each player gets movement and one action per turn.':'Each player gets movement and one action per turn.';
 $('#tableStatus').textContent=Date.now()<noticeUntil?notice:state.error|| (state.busy?'Astra is weaving the next moment…':'');
}
async function command(path,body){if(!session||sending)return;sending=true;render();try{apply(await api(`/rooms/${session.code}/${path}`,{method:'POST',body}));noticeUntil=0;}catch(e){message(e.message)}finally{sending=false;render()}}
function act(kind,extra={}){if(!myTurn())return;return command('action',{kind,actionId:crypto.randomUUID(),...extra})}
function chooseTarget(id){if(!myTurn())return;const kind=['attack','heal','interact'].includes(mode)?mode:'attack';act(kind,{targetId:id})}
$('#targetAction').onclick=()=>chooseTarget($('#targetPicker').value);for(const b of document.querySelectorAll('[data-step]'))b.onclick=()=>{if(!myTurn())return;const [dx,dy]=b.dataset.step.split(',').map(Number),p=state.players.find(p=>p.id===session.playerId);act('move',{x:p.x+dx,y:p.y+dy})};
$('#roomMenuButton').onclick=()=>$('#roomDialog').showModal();$('#closeRoom').onclick=()=>$('#roomDialog').close();$('#startAdventure').onclick=()=>{command('start',{});$('#roomDialog').close()};
$('#leaveRoom').onclick=async()=>{if(sending)return;try{await api(`/rooms/${session.code}/leave`,{method:'POST',body:{}});saveSession(null);state=null;sceneKey='';lastLog='';$('#roomDialog').close();$('#gameHud').hidden=true;$('#lobby').hidden=false;$('#lobbyError').textContent='You left the table.';terrain=background(lobbyScene);}catch(e){message(e.message)}};
$('#copyInvite').onclick=async()=>{const url=new URL(location.href);url.searchParams.set('room',state.code);try{await navigator.clipboard.writeText(url.toString());$('#roomHelp').textContent='Invite link copied.'}catch{$('#roomHelp').textContent=`Share this code: ${state.code}`}};
$('#toggleChronicle').onclick=()=>{const collapsed=$('#chronicle').classList.toggle('collapsed');$('#toggleChronicle').setAttribute('aria-expanded',String(!collapsed));};
$('#chatForm').onsubmit=async e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;try{apply(await api(`/rooms/${session.code}/chat`,{method:'POST',body:{text}}));input.value=''}catch(e){message(e.message)}};
$('#improviseForm').onsubmit=e=>{e.preventDefault();const text=$('#actionIdea').value.trim();if(text&&myTurn())act('improvise',{text}).then(()=>{if(state?.busy)$('#actionIdea').value=''})};
for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>{const kind=b.dataset.action;if(kind==='guard'||kind==='end')act(kind,{targetId:session.playerId});else{mode=kind;render()}};
function camera(){if(!state?.scene||!matchMedia('(max-width:650px)').matches)return{x:0,y:0};const me=state.players.find(p=>p.id===session?.playerId);return{x:Math.max(-185,Math.min(185,(me?.x||400)-400)),y:Math.max(0,Math.min(200,(me?.y||400)-245))}}
function screenPoint(e){const r=canvas.getBoundingClientRect(),scale=Math.max(r.width/800,r.height/600);return {x:(e.clientX-r.left-(r.width-800*scale)/2)/scale+camera().x,y:(e.clientY-r.top-(r.height-600*scale)/2)/scale+camera().y};}
canvas.onclick=e=>{if(!myTurn())return;const p=screenPoint(e);if(mode==='move'){act('move',{x:Math.round(p.x),y:Math.round(p.y)});return}const candidates=mode==='heal'?state.players:mode==='interact'?state.scene.props:state.scene.creatures;const target=[...candidates].sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(target&&Math.hypot(target.x-p.x,target.y-p.y)<65)chooseTarget(target.id);else message('Select a target, or choose Move to walk there.')};
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea')||$('#roomDialog').open||!myTurn())return;const d={w:[0,-20],ArrowUp:[0,-20],s:[0,20],ArrowDown:[0,20],a:[-20,0],ArrowLeft:[-20,0],d:[20,0],ArrowRight:[20,0]}[e.key];if(d){e.preventDefault();const p=state.players.find(p=>p.id===session.playerId);act('move',{x:p.x+d[0],y:p.y+d[1]})}});
export function paint(now=performance.now()){if(now-lastFrame>32){lastFrame=now;ctx.fillStyle='#102023';ctx.fillRect(0,0,800,600);ctx.save();const offset=camera();ctx.translate(-offset.x,-offset.y);ctx.drawImage(terrain,0,0);const scene=state?.scene;if(scene){for(const p of scene.props){ctx.strokeStyle=p.secured?'#8ab99e':'#e8c385';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y+10,20,7,0,0,Math.PI*2);ctx.stroke();if(p.secured){ctx.font='20px VT323';ctx.fillStyle='#b7dab2';ctx.fillText('✓',p.x-5,p.y-35)}}for(const e of scene.creatures)creature(ctx,e,reduced.matches?0:now);}
 const party=state?.players||[];for(const [i,p] of party.entries()){let display=scene?p:{...p,x:320+i*60,y:355};const old=positions.get(p.id)||{x:display.x,y:display.y};const moving=Math.hypot(old.x-display.x,old.y-display.y)>1;if(!reduced.matches&&moving){old.x+=(display.x-old.x)*.3;old.y+=(display.y-old.y)*.3;display={...display,x:old.x,y:old.y,walking:true}}else Object.assign(old,{x:display.x,y:display.y});positions.set(p.id,old);hero(ctx,display,now,state?.turn===p.id&&state.phase==='playing',effects.findLast(e=>e.from.id===p.id&&now-e.localTime<900));}
 if(!state){creature(ctx,{id:'lobby-dragon',name:'',kind:'dragon',x:570,y:300,color:'#627759',hp:1,maxHp:1},reduced.matches?0:now)}
 for(const e of effects)effect(ctx,e,now,reduced.matches);while(effects.length&&now-effects[0].localTime>1200)effects.shift();if(state&&Date.now()>noticeUntil&&notice){notice='';render()}ctx.restore()}
}
function animate(now){paint(now);requestAnimationFrame(animate)}
paint();requestAnimationFrame(animate);
try{const stored=JSON.parse(sessionStorage.getItem('tilth-table-seat'));if(stored?.code&&stored.token){session=stored;poll()}}catch{}
